# Auto-generated from 📊 V25_CDC_DELIVERY_TRACKER.csv for MVP QAIC Reflex.
# Local/static read-only payload. No Sheets/BQ write, no Apps Script exec, no broker/order/sizing.
from __future__ import annotations

REAL_COCKPIT_MARKER = "V25_CDC_DELIVERY_TRACKER_COCKPIT"
SOURCE_SHEET = "📊 V25_CDC_DELIVERY_TRACKER"
SOURCE_MODE = "STATIC_EXPORT_READONLY"

GLOBAL_META = {'sheet_title': '📊 QAIC CDC DELIVERY TRACKER — AVANCEMENT + PLANNING',
 'source_ledger': 'QAIC_CDC1R_LIVE_EVIDENCE_LEDGER_0.4.5_P3_59_SOURCE_LEDGER_PREFERENCE_SAFE',
 'updated': '2026-06-15 19:41:10',
 'global_status': 'REVIEW',
 'realized_pct': '73.25%',
 'estimated_h': '372',
 'remaining_h': '99,5',
 'blocked': '1',
 'at_risk': '50',
 'detail_rows': '85',
 'source': '🧭 QAIC_CDC_SOURCE_LEDGER',
 'source_mode': 'PERSISTENT_CDC_SOURCE_LEDGER',
 'detail_mode': 'MODULE_GATE_ONLY',
 'done_h': '272,5',
 'p10_python': 'EVIDENCE_TAGGED_NO_FAKE_REALTIME',
 'safety': 'HUMAN_REVIEW_ONLY_NO_AUTO_ORDER_NO_AUTO_SIZING_NO_BROKER_EXECUTION_NO_REAL_ORDER_NO_BIGQUERY_WRITE_NO_TRIGGER_MUTATION',
 'decision': 'Corriger / valider les lignes REVIEW, MISSING ou BLOCKED avant CDC-2.',
 'guardrail': 'No broker / no BQ / no trigger / no auto apply.',
 'pilotage': 'Lignes 5-6 = premier tableau QAIT-style : TOTAL + sous-totaux phase. Aucun séparateur vide.'}

SUMMARY_ROWS = [{'phase_id': 'TOTAL',
  'phase_name': 'TOTAL_QAIC_ALL_PHASES',
  'items': '85',
  'realized_pct': '73,3%',
  'estimated_h': '372,00',
  'remaining_h': '99,50',
  'done': '33',
  'review': '35',
  'missing': '15',
  'planned': '1',
  'blocked': '1',
  'critical_path': '15',
  'next_action': 'Corriger en priorité avant nouvelle brique V25.',
  'realized_num': 73.3},
 {'phase_id': 'P00',
  'phase_name': 'P00 — Control Plane & Governance',
  'items': '7',
  'realized_pct': '64,0%',
  'estimated_h': '46,00',
  'remaining_h': '16,55',
  'done': '3',
  'review': '2',
  'missing': '1',
  'planned': '0',
  'blocked': '1,0%',
  'critical_path': '5',
  'next_action': 'Corriger en priorité avant nouvelle brique V25.',
  'realized_num': 64.0},
 {'phase_id': 'P01',
  'phase_name': 'P01 — Reference Contracts & Registries',
  'items': '6',
  'realized_pct': '70,0%',
  'estimated_h': '30,00',
  'remaining_h': '9,00',
  'done': '0',
  'review': '6',
  'missing': '0',
  'planned': '0',
  'blocked': '0,0%',
  'critical_path': '0',
  'next_action': "Relancer l'audit du module puis arbitrer.",
  'realized_num': 70.0},
 {'phase_id': 'P02',
  'phase_name': 'P02 — Identity, Taxonomy & Data Quality',
  'items': '7',
  'realized_pct': '89,6%',
  'estimated_h': '36,00',
  'remaining_h': '3,75',
  'done': '5',
  'review': '1',
  'missing': '1',
  'planned': '0',
  'blocked': '0,0%',
  'critical_path': '1',
  'next_action': "Relancer l'audit du module puis arbitrer.",
  'realized_num': 89.6},
 {'phase_id': 'P03',
  'phase_name': 'P03 — Market Data Pipeline',
  'items': '12',
  'realized_pct': '100,0%',
  'estimated_h': '43,00',
  'remaining_h': '0,00',
  'done': '12',
  'review': '0',
  'missing': '0',
  'planned': '0',
  'blocked': '0,0%',
  'critical_path': '1',
  'next_action': 'KEEP_MONITOR',
  'realized_num': 100.0},
 {'phase_id': 'P04',
  'phase_name': 'P04 — Alpha Design & Readiness',
  'items': '5',
  'realized_pct': '77,1%',
  'estimated_h': '21,00',
  'remaining_h': '4,80',
  'done': '1',
  'review': '4',
  'missing': '0',
  'planned': '0',
  'blocked': '0,0%',
  'critical_path': '0',
  'next_action': "Relancer l'audit du module puis arbitrer.",
  'realized_num': 77.1},
 {'phase_id': 'P05',
  'phase_name': 'P05 — Portfolio, Dashboards & Roadmap',
  'items': '5',
  'realized_pct': '66,7%',
  'estimated_h': '9,00',
  'remaining_h': '3,00',
  'done': '4',
  'review': '0',
  'missing': '0',
  'planned': '1',
  'blocked': '0,0%',
  'critical_path': '0',
  'next_action': 'Roadmap / futur : ne pas traiter maintenant sauf décision JRb.',
  'realized_num': 66.7},
 {'phase_id': 'P06',
  'phase_name': 'P06 — Market Regime & Alpha Modulation',
  'items': '2',
  'realized_pct': '85,0%',
  'estimated_h': '10,00',
  'remaining_h': '1,50',
  'done': '1',
  'review': '1',
  'missing': '0',
  'planned': '0',
  'blocked': '0,0%',
  'critical_path': '0',
  'next_action': "Relancer l'audit du module puis arbitrer.",
  'realized_num': 85.0},
 {'phase_id': 'P07',
  'phase_name': 'P07 — Portfolio Alpha & Execution Governance',
  'items': '11',
  'realized_pct': '64,9%',
  'estimated_h': '56,00',
  'remaining_h': '19,65',
  'done': '2',
  'review': '6',
  'missing': '3',
  'planned': '0',
  'blocked': '0,0%',
  'critical_path': '1',
  'next_action': "Relancer l'audit du module puis arbitrer.",
  'realized_num': 64.9},
 {'phase_id': 'P08',
  'phase_name': 'P08 — Revolut X Broker Readonly & Fiscal',
  'items': '5',
  'realized_pct': '77,0%',
  'estimated_h': '30,00',
  'remaining_h': '6,90',
  'done': '2',
  'review': '1',
  'missing': '2',
  'planned': '0',
  'blocked': '0,0%',
  'critical_path': '3',
  'next_action': "Relancer l'audit du module puis arbitrer.",
  'realized_num': 77.0},
 {'phase_id': 'P09',
  'phase_name': 'P09 — Governance Refresh & Clean',
  'items': '1',
  'realized_pct': '25,0%',
  'estimated_h': '8,00',
  'remaining_h': '6,00',
  'done': '0',
  'review': '0',
  'missing': '1',
  'planned': '0',
  'blocked': '0,0%',
  'critical_path': '1',
  'next_action': 'Créer ou relancer le module attendu.',
  'realized_num': 25.0},
 {'phase_id': 'P10',
  'phase_name': 'P10 — Python Migration & Live Evidence',
  'items': '1',
  'realized_pct': '100,0%',
  'estimated_h': '8,00',
  'remaining_h': '0,00',
  'done': '1',
  'review': '0',
  'missing': '0',
  'planned': '0',
  'blocked': '0,0%',
  'critical_path': '1',
  'next_action': 'KEEP_MONITOR',
  'realized_num': 100.0},
 {'phase_id': 'P11',
  'phase_name': 'P11 — Registry Live Evidence',
  'items': '1',
  'realized_pct': '100,0%',
  'estimated_h': '6,00',
  'remaining_h': '0,00',
  'done': '1',
  'review': '0',
  'missing': '0',
  'planned': '0',
  'blocked': '0,0%',
  'critical_path': '1',
  'next_action': 'KEEP_MONITOR',
  'realized_num': 100.0},
 {'phase_id': 'P12',
  'phase_name': 'P12 — Data Quality Live Gate',
  'items': '1',
  'realized_pct': '100,0%',
  'estimated_h': '6,00',
  'remaining_h': '0,00',
  'done': '1',
  'review': '0',
  'missing': '0',
  'planned': '0',
  'blocked': '0,0%',
  'critical_path': '1',
  'next_action': 'KEEP_MONITOR',
  'realized_num': 100.0},
 {'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'items': '21',
  'realized_pct': '55,0%',
  'estimated_h': '63,00',
  'remaining_h': '28,35',
  'done': '0',
  'review': '14',
  'missing': '7',
  'planned': '0',
  'blocked': '0,0%',
  'critical_path': '0',
  'next_action': "Relancer l'audit du module puis arbitrer.",
  'realized_num': 55.0}]

DETAIL_ROWS = [{'decision_status': 'DONE',
  'priority': 'P3',
  'phase_id': 'P00',
  'phase_name': 'P00 — Control Plane & Governance',
  'module_id': 'AGOV-00-SAFE-MENU',
  'module_name': 'V25 Safe Menu Draft',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'V25 Safe Menu Draft — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '1,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'BLOCKED',
  'priority': 'P0',
  'phase_id': 'P00',
  'phase_name': 'P00 — Control Plane & Governance',
  'module_id': 'PMT-0001',
  'module_name': 'Global Contract Crypto Alpha IA / System Contract',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Global Contract Crypto Alpha IA / System Contract — module governance gate',
  'realized_pct': '0,0%',
  'remaining_effort_hours': '8,00',
  'estimated_effort_hours_nominal': '8,00',
  'realized_level': 'NONE',
  'schedule_status': 'BLOCKED',
  'schedule_risk': 'HIGH',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '1',
  'dependency_status': 'BLOCKED',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 0.0},
 {'decision_status': 'REVIEW',
  'priority': 'P0',
  'phase_id': 'P00',
  'phase_name': 'P00 — Control Plane & Governance',
  'module_id': 'PMT-0002',
  'module_name': 'Alert Control Center',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Alert Control Center — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '2,40',
  'estimated_effort_hours_nominal': '8,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'HIGH',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'DONE',
  'priority': 'P0',
  'phase_id': 'P00',
  'phase_name': 'P00 — Control Plane & Governance',
  'module_id': 'PMT-0003',
  'module_name': 'System Source Script Audit',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'System Source Script Audit — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '8,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P0',
  'phase_id': 'P00',
  'phase_name': 'P00 — Control Plane & Governance',
  'module_id': 'PMT-0004',
  'module_name': 'Central Trigger Manager',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'Central Trigger Manager — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '8,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'REVIEW',
  'priority': 'P0',
  'phase_id': 'P00',
  'phase_name': 'P00 — Control Plane & Governance',
  'module_id': 'PMT-0005',
  'module_name': 'Phase Module Tracker',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Phase Module Tracker — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '2,40',
  'estimated_effort_hours_nominal': '8,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'HIGH',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'MISSING',
  'priority': 'P1',
  'phase_id': 'P00',
  'phase_name': 'P00 — Control Plane & Governance',
  'module_id': 'PMT-0006',
  'module_name': 'Script Registry & Legacy Coverage',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Script Registry & Legacy Coverage — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '3,75',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 25.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P01',
  'phase_name': 'P01 — Reference Contracts & Registries',
  'module_id': 'PMT-0101',
  'module_name': 'API Source Registry',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'API Source Registry — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P01',
  'phase_name': 'P01 — Reference Contracts & Registries',
  'module_id': 'PMT-0102',
  'module_name': 'Data Lineage Map',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'Data Lineage Map — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P01',
  'phase_name': 'P01 — Reference Contracts & Registries',
  'module_id': 'PMT-0103',
  'module_name': 'Score Version Registry',
  'target_layer': 'ALPHA_SCORING',
  'deliverable_name': 'Score Version Registry — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P01',
  'phase_name': 'P01 — Reference Contracts & Registries',
  'module_id': 'PMT-0104',
  'module_name': 'Model Governance Registry',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Model Governance Registry — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P01',
  'phase_name': 'P01 — Reference Contracts & Registries',
  'module_id': 'PMT-0105',
  'module_name': 'Experiment Registry',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'Experiment Registry — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P01',
  'phase_name': 'P01 — Reference Contracts & Registries',
  'module_id': 'PMT-0106',
  'module_name': 'Legacy Retirement Register',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Legacy Retirement Register — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'JRb',
  'realized_num': 70.0},
 {'decision_status': 'DONE',
  'priority': 'P0',
  'phase_id': 'P02',
  'phase_name': 'P02 — Identity, Taxonomy & Data Quality',
  'module_id': 'PMT-0201',
  'module_name': 'Asset Identity Map',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'Asset Identity Map — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '8,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P1',
  'phase_id': 'P02',
  'phase_name': 'P02 — Identity, Taxonomy & Data Quality',
  'module_id': 'PMT-0202',
  'module_name': 'Price Source Availability Audit',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'Price Source Availability Audit — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P1',
  'phase_id': 'P02',
  'phase_name': 'P02 — Identity, Taxonomy & Data Quality',
  'module_id': 'PMT-0203',
  'module_name': 'Manual Identity Decisions',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Manual Identity Decisions — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'JRb',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P1',
  'phase_id': 'P02',
  'phase_name': 'P02 — Identity, Taxonomy & Data Quality',
  'module_id': 'PMT-0204',
  'module_name': 'Manual Scoring Policy Audit',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Manual Scoring Policy Audit — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P1',
  'phase_id': 'P02',
  'phase_name': 'P02 — Identity, Taxonomy & Data Quality',
  'module_id': 'PMT-0205',
  'module_name': 'Taxonomy Coverage Audit',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'Taxonomy Coverage Audit — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P02',
  'phase_name': 'P02 — Identity, Taxonomy & Data Quality',
  'module_id': 'PMT-0206',
  'module_name': 'Taxonomy Rules Registry',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'Taxonomy Rules Registry — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'MISSING',
  'priority': 'P2',
  'phase_id': 'P02',
  'phase_name': 'P02 — Identity, Taxonomy & Data Quality',
  'module_id': 'PMT-0207',
  'module_name': 'Taxonomy Manual Decisions',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Taxonomy Manual Decisions — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '2,25',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'JRb',
  'realized_num': 25.0},
 {'decision_status': 'DONE',
  'priority': 'P2',
  'phase_id': 'P03',
  'phase_name': 'P03 — Market Data Pipeline',
  'module_id': 'AGOV-3A-NORMALIZED',
  'module_name': 'V25 Normalized Engine',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'V25 Normalized Engine — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P2',
  'phase_id': 'P03',
  'phase_name': 'P03 — Market Data Pipeline',
  'module_id': 'AGOV-3B-MARKET-SCORES',
  'module_name': 'V25 Market Scores Engine',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'V25 Market Scores Engine — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P2',
  'phase_id': 'P03',
  'phase_name': 'P03 — Market Data Pipeline',
  'module_id': 'AGOV-3C-ALPHA-RANKING',
  'module_name': 'V25 Alpha Ranking View',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'V25 Alpha Ranking View — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P2',
  'phase_id': 'P03',
  'phase_name': 'P03 — Market Data Pipeline',
  'module_id': 'AGOV-3D-ALPHA-SIGNAL',
  'module_name': 'V25 Alpha Signal Decision',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'V25 Alpha Signal Decision — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P3',
  'phase_id': 'P03',
  'phase_name': 'P03 — Market Data Pipeline',
  'module_id': 'AGOV-3E-ALPHA-COCKPIT',
  'module_name': 'V25 Alpha Decision Cockpit',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'V25 Alpha Decision Cockpit — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '1,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P3',
  'phase_id': 'P03',
  'phase_name': 'P03 — Market Data Pipeline',
  'module_id': 'AGOV-3F-ALPHA-PIPELINE',
  'module_name': 'V25 Alpha Pipeline Integration',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'V25 Alpha Pipeline Integration — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '1,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P0',
  'phase_id': 'P03',
  'phase_name': 'P03 — Market Data Pipeline',
  'module_id': 'PMT-0301',
  'module_name': 'Market Data Master',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'Market Data Master — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '8,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P1',
  'phase_id': 'P03',
  'phase_name': 'P03 — Market Data Pipeline',
  'module_id': 'PMT-0302',
  'module_name': 'CoinGecko RAW / Identity Index',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'CoinGecko RAW / Identity Index — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P1',
  'phase_id': 'P03',
  'phase_name': 'P03 — Market Data Pipeline',
  'module_id': 'PMT-0303',
  'module_name': 'Binance RAW Fast',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'Binance RAW Fast — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P2',
  'phase_id': 'P03',
  'phase_name': 'P03 — Market Data Pipeline',
  'module_id': 'PMT-0304',
  'module_name': 'Futures RAW / Aggregated',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'Futures RAW / Aggregated — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P2',
  'phase_id': 'P03',
  'phase_name': 'P03 — Market Data Pipeline',
  'module_id': 'PMT-0305',
  'module_name': 'DefiLlama RAW',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'DefiLlama RAW — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P1',
  'phase_id': 'P03',
  'phase_name': 'P03 — Market Data Pipeline',
  'module_id': 'PMT-0306',
  'module_name': 'Metric Registry',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'Metric Registry — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P04',
  'phase_name': 'P04 — Alpha Design & Readiness',
  'module_id': 'PMT-0401',
  'module_name': 'Alpha Readiness Gate',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'Alpha Readiness Gate — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'DONE',
  'priority': 'P1',
  'phase_id': 'P04',
  'phase_name': 'P04 — Alpha Design & Readiness',
  'module_id': 'PMT-0402',
  'module_name': 'Alpha Engine Design',
  'target_layer': 'ALPHA_SCORING',
  'deliverable_name': 'Alpha Engine Design — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P04',
  'phase_name': 'P04 — Alpha Design & Readiness',
  'module_id': 'PMT-0403',
  'module_name': 'Alpha Feature Registry',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'Alpha Feature Registry — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P3',
  'phase_id': 'P04',
  'phase_name': 'P04 — Alpha Design & Readiness',
  'module_id': 'PMT-0404',
  'module_name': 'Alpha Score Engine Draft — LEGACY NEUTRALIZED',
  'target_layer': 'LEGACY_ARCHIVE_GOVERNANCE',
  'deliverable_name': 'Alpha Score Engine Draft — LEGACY NEUTRALIZED — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,30',
  'estimated_effort_hours_nominal': '1,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P04',
  'phase_name': 'P04 — Alpha Design & Readiness',
  'module_id': 'PMT-0405',
  'module_name': 'Alpha Backtest Validation — OFFICIAL V25_38',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'Alpha Backtest Validation — OFFICIAL V25_38 — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'DONE',
  'priority': 'P2',
  'phase_id': 'P05',
  'phase_name': 'P05 — Portfolio, Dashboards & Roadmap',
  'module_id': 'PMT-0501',
  'module_name': 'Portfolio Source of Truth',
  'target_layer': 'DATA_PIPELINE',
  'deliverable_name': 'Portfolio Source of Truth — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'JRb',
  'realized_num': 100.0},
 {'decision_status': 'PLANNED',
  'priority': 'P2',
  'phase_id': 'P05',
  'phase_name': 'P05 — Portfolio, Dashboards & Roadmap',
  'module_id': 'PMT-0502',
  'module_name': 'Executive Dashboard',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'Executive Dashboard — module governance gate',
  'realized_pct': '0,0%',
  'remaining_effort_hours': '3,00',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'NONE',
  'schedule_status': 'PLANNED',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'JRb',
  'realized_num': 0.0},
 {'decision_status': 'DONE',
  'priority': 'P3',
  'phase_id': 'P05',
  'phase_name': 'P05 — Portfolio, Dashboards & Roadmap',
  'module_id': 'PMT-0503',
  'module_name': 'Historical Storage / BigQuery Readiness',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'Historical Storage / BigQuery Readiness — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '1,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'JRb',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P3',
  'phase_id': 'P05',
  'phase_name': 'P05 — Portfolio, Dashboards & Roadmap',
  'module_id': 'PMT-0504',
  'module_name': 'Python / Cloud Run Compute',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'Python / Cloud Run Compute — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '1,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P3',
  'phase_id': 'P05',
  'phase_name': 'P05 — Portfolio, Dashboards & Roadmap',
  'module_id': 'PMT-0505',
  'module_name': 'AI Decision Support',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'AI Decision Support — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '1,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'JRb',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P1',
  'phase_id': 'P06',
  'phase_name': 'P06 — Market Regime & Alpha Modulation',
  'module_id': 'PMT-0601',
  'module_name': 'Market Regime Engine',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'Market Regime Engine — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P06',
  'phase_name': 'P06 — Market Regime & Alpha Modulation',
  'module_id': 'PMT-0602',
  'module_name': 'Alpha Regime Modulator',
  'target_layer': 'ALPHA_SCORING',
  'deliverable_name': 'Alpha Regime Modulator — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P07',
  'phase_name': 'P07 — Portfolio Alpha & Execution Governance',
  'module_id': 'PMT-0701',
  'module_name': 'Portfolio Alpha Bridge',
  'target_layer': 'PORTFOLIO_RISK',
  'deliverable_name': 'Portfolio Alpha Bridge — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'MISSING',
  'priority': 'P1',
  'phase_id': 'P07',
  'phase_name': 'P07 — Portfolio Alpha & Execution Governance',
  'module_id': 'PMT-0702',
  'module_name': 'Portfolio Master Builder',
  'target_layer': 'PORTFOLIO_RISK',
  'deliverable_name': 'Portfolio Master Builder — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '3,75',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 25.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P07',
  'phase_name': 'P07 — Portfolio Alpha & Execution Governance',
  'module_id': 'PMT-0703',
  'module_name': 'Portfolio Exposure Engine',
  'target_layer': 'PORTFOLIO_RISK',
  'deliverable_name': 'Portfolio Exposure Engine — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P07',
  'phase_name': 'P07 — Portfolio Alpha & Execution Governance',
  'module_id': 'PMT-0704',
  'module_name': 'Portfolio Risk Decision Engine',
  'target_layer': 'PORTFOLIO_RISK',
  'deliverable_name': 'Portfolio Risk Decision Engine — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P07',
  'phase_name': 'P07 — Portfolio Alpha & Execution Governance',
  'module_id': 'PMT-0705',
  'module_name': 'Portfolio Decision Control Center',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Portfolio Decision Control Center — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'DONE',
  'priority': 'P1',
  'phase_id': 'P07',
  'phase_name': 'P07 — Portfolio Alpha & Execution Governance',
  'module_id': 'PMT-0706',
  'module_name': 'Portfolio Execution Queue',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Portfolio Execution Queue — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P0',
  'phase_id': 'P07',
  'phase_name': 'P07 — Portfolio Alpha & Execution Governance',
  'module_id': 'PMT-0707',
  'module_name': 'Portfolio Pre-Trade Guard',
  'target_layer': 'BROKER_EXECUTION_GOVERNANCE',
  'deliverable_name': 'Portfolio Pre-Trade Guard — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '8,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'MISSING',
  'priority': 'P1',
  'phase_id': 'P07',
  'phase_name': 'P07 — Portfolio Alpha & Execution Governance',
  'module_id': 'PMT-0708',
  'module_name': 'Manual Order Ticket Builder',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Manual Order Ticket Builder — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '3,75',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'JRb',
  'realized_num': 25.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P07',
  'phase_name': 'P07 — Portfolio Alpha & Execution Governance',
  'module_id': 'PMT-0709',
  'module_name': 'Manual Order Lifecycle Tracker',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Manual Order Lifecycle Tracker — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'JRb',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P1',
  'phase_id': 'P07',
  'phase_name': 'P07 — Portfolio Alpha & Execution Governance',
  'module_id': 'PMT-0710',
  'module_name': 'Post-Trade Reconciliation Engine',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'Post-Trade Reconciliation Engine — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '1,50',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'MISSING',
  'priority': 'P1',
  'phase_id': 'P07',
  'phase_name': 'P07 — Portfolio Alpha & Execution Governance',
  'module_id': 'PMT-0711',
  'module_name': 'V25 Order Log',
  'target_layer': 'BROKER_EXECUTION_GOVERNANCE',
  'deliverable_name': 'V25 Order Log — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '3,75',
  'estimated_effort_hours_nominal': '5,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 25.0},
 {'decision_status': 'DONE',
  'priority': 'P0',
  'phase_id': 'P08',
  'phase_name': 'P08 — Revolut X Broker Readonly & Fiscal',
  'module_id': 'PMT-0801',
  'module_name': 'Revolut API Readiness Contract',
  'target_layer': 'BROKER_EXECUTION_GOVERNANCE',
  'deliverable_name': 'Revolut API Readiness Contract — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '8,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P0',
  'phase_id': 'P08',
  'phase_name': 'P08 — Revolut X Broker Readonly & Fiscal',
  'module_id': 'PMT-0802',
  'module_name': 'Revolut X Readonly Connector',
  'target_layer': 'BROKER_EXECUTION_GOVERNANCE',
  'deliverable_name': 'Revolut X Readonly Connector — module governance gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '8,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'REVIEW',
  'priority': 'P0',
  'phase_id': 'P08',
  'phase_name': 'P08 — Revolut X Broker Readonly & Fiscal',
  'module_id': 'PMT-0803',
  'module_name': 'Revolut Fiscal Ledger Builder',
  'target_layer': 'FISCAL_REPORTING',
  'deliverable_name': 'Revolut Fiscal Ledger Builder — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '2,40',
  'estimated_effort_hours_nominal': '8,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'HIGH',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'MISSING',
  'priority': 'P2',
  'phase_id': 'P08',
  'phase_name': 'P08 — Revolut X Broker Readonly & Fiscal',
  'module_id': 'V25_29',
  'module_name': '1 REVOLUT API SECURITY HARDENING',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': '1 REVOLUT API SECURITY HARDENING — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '2,25',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 25.0},
 {'decision_status': 'MISSING',
  'priority': 'P2',
  'phase_id': 'P08',
  'phase_name': 'P08 — Revolut X Broker Readonly & Fiscal',
  'module_id': 'V25_30',
  'module_name': 'REVOLUT EXTERNAL SIGNER CONTRACT',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'REVOLUT EXTERNAL SIGNER CONTRACT — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '2,25',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 25.0},
 {'decision_status': 'MISSING',
  'priority': 'P0',
  'phase_id': 'P09',
  'phase_name': 'P09 — Governance Refresh & Clean',
  'module_id': 'PMT-0901',
  'module_name': 'Governance Refresh Orchestrator',
  'target_layer': 'GOVERNANCE_CONTROL_PLANE',
  'deliverable_name': 'Governance Refresh Orchestrator — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '6,00',
  'estimated_effort_hours_nominal': '8,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'HIGH',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 25.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_00',
  'module_name': 'REFERENCE STANDARDS',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'REFERENCE STANDARDS — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'MISSING',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_14',
  'module_name': 'ALPHA FACTOR ENGINE',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'ALPHA FACTOR ENGINE — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '2,25',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 25.0},
 {'decision_status': 'MISSING',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_15',
  'module_name': 'NORMALIZATION ENGINE',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'NORMALIZATION ENGINE — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '2,25',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 25.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_16',
  'module_name': 'ALPHA CONTROL CENTER',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'ALPHA CONTROL CENTER — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'MISSING',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_17',
  'module_name': 'ALPHA SCORE ENGINE',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'ALPHA SCORE ENGINE — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '2,25',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 25.0},
 {'decision_status': 'MISSING',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_18',
  'module_name': 'ALPHA SIGNAL ENGINE',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'ALPHA SIGNAL ENGINE — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '2,25',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 25.0},
 {'decision_status': 'MISSING',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_19',
  'module_name': 'RISK ENGINE',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'RISK ENGINE — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '2,25',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 25.0},
 {'decision_status': 'MISSING',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_20',
  'module_name': 'PORTFOLIO QUANT ENGINE',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'PORTFOLIO QUANT ENGINE — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '2,25',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 25.0},
 {'decision_status': 'MISSING',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_23',
  'module_name': 'IA REPORT ENGINE',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'IA REPORT ENGINE — module governance gate',
  'realized_pct': '25,0%',
  'remaining_effort_hours': '2,25',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'LOW',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 25.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_28',
  'module_name': 'ORDER LOG V25 BUILDER',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'ORDER LOG V25 BUILDER — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_32',
  'module_name': 'GLOBAL MODULE RATIONALIZATION AUDIT',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'GLOBAL MODULE RATIONALIZATION AUDIT — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_33',
  'module_name': 'EXECUTIVE CONTROL CENTER',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'EXECUTIVE CONTROL CENTER — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_34',
  'module_name': 'ALPHA CONVICTION ENGINE',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'ALPHA CONVICTION ENGINE — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_35',
  'module_name': 'PORTFOLIO INTELLIGENCE',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'PORTFOLIO INTELLIGENCE — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_36',
  'module_name': 'HIST DAILY SNAPSHOTS',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'HIST DAILY SNAPSHOTS — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_37',
  'module_name': 'BACKTEST ENGINE',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'BACKTEST ENGINE — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_39',
  'module_name': 'ALPHA ATTRIBUTION ENGINE',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'ALPHA ATTRIBUTION ENGINE — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_3A',
  'module_name': 'CREATE FINAL RAW SHEETS',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'CREATE FINAL RAW SHEETS — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_3G',
  'module_name': 'ALPHA GOVERNANCE REGISTRY PATCH',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'ALPHA GOVERNANCE REGISTRY PATCH — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_3H',
  'module_name': 'ALPHA GOVERNANCE APPLY SAFE',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'ALPHA GOVERNANCE APPLY SAFE — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'REVIEW',
  'priority': 'P2',
  'phase_id': 'P99',
  'phase_name': 'P99 — Auto-Discovered / Review Required',
  'module_id': 'V25_3I',
  'module_name': 'ALPHA GOVERNANCE GLOBAL RECONCILE SAFE',
  'target_layer': 'MODULE_GOVERNANCE',
  'deliverable_name': 'ALPHA GOVERNANCE GLOBAL RECONCILE SAFE — module governance gate',
  'realized_pct': '70,0%',
  'remaining_effort_hours': '0,90',
  'estimated_effort_hours_nominal': '3,00',
  'realized_level': 'MEDIUM',
  'schedule_status': 'WATCH',
  'schedule_risk': 'MEDIUM',
  'critical_path_flag': 'FALSE',
  'blocking_dependency_count': '0',
  'dependency_status': 'WATCH',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 70.0},
 {'decision_status': 'DONE',
  'priority': 'P0',
  'phase_id': 'P10',
  'phase_name': 'P10 — Python Migration & Live Evidence',
  'module_id': 'PY-LIVE-0001',
  'module_name': 'QAIC_PY live repo evidence bridge',
  'target_layer': 'PYTHON_LIVE_EVIDENCE',
  'deliverable_name': 'QAIC_PY branch/head/worktree/test status exported read-only to Drive and imported in CDC',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '8,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P0',
  'phase_id': 'P11',
  'phase_name': 'P11 — Registry Live Evidence',
  'module_id': 'REG-LIVE-0001',
  'module_name': 'Script Registry live evidence',
  'target_layer': 'SCRIPT_REGISTRY_LIVE',
  'deliverable_name': 'Live Script Registry sheet evidence wired into CDC',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '6,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0},
 {'decision_status': 'DONE',
  'priority': 'P0',
  'phase_id': 'P12',
  'phase_name': 'P12 — Data Quality Live Gate',
  'module_id': 'DQ-LIVE-0001',
  'module_name': 'Data Quality live CDC gate evidence',
  'target_layer': 'DATA_QUALITY_LIVE_GATE',
  'deliverable_name': 'Live DQ/Quality Gate evidence wired into CDC final gate',
  'realized_pct': '100,0%',
  'remaining_effort_hours': '0,00',
  'estimated_effort_hours_nominal': '6,00',
  'realized_level': 'DONE',
  'schedule_status': 'ON_TRACK',
  'schedule_risk': 'LOW',
  'critical_path_flag': 'TRUE',
  'blocking_dependency_count': '0',
  'dependency_status': 'CLEAR',
  'target_delivery_date': '',
  'delay_days': '0',
  'owner': 'SYSTEM',
  'realized_num': 100.0}]


def pct_value(value: object) -> int:
    raw = str(value).replace("%", "").replace(",", ".").strip()
    try:
        return max(0, min(100, int(round(float(raw)))))
    except Exception:
        return 0


def global_progress_pct() -> int:
    return pct_value(GLOBAL_META.get("realized_pct", "0"))


def critical_detail_rows(limit: int = 14) -> list[dict[str, object]]:
    priority_order = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
    status_order = {"BLOCKED": 0, "REVIEW": 1, "MISSING": 2, "PLANNED": 3, "DONE": 9}
    rows = sorted(
        DETAIL_ROWS,
        key=lambda row: (
            priority_order.get(str(row.get("priority", "P9")), 9),
            status_order.get(str(row.get("decision_status", "REVIEW")), 5),
            -float(row.get("remaining_effort_hours", "0").replace(",", ".") or 0),
        ),
    )
    return rows[:limit]


def phase_rows() -> list[dict[str, object]]:
    return SUMMARY_ROWS


def cdc_kpis() -> dict[str, object]:
    return {
        "status": GLOBAL_META.get("global_status", "REVIEW"),
        "realized_pct": GLOBAL_META.get("realized_pct", "0%"),
        "realized_num": global_progress_pct(),
        "estimated_h": GLOBAL_META.get("estimated_h", ""),
        "done_h": GLOBAL_META.get("done_h", ""),
        "remaining_h": GLOBAL_META.get("remaining_h", ""),
        "blocked": GLOBAL_META.get("blocked", ""),
        "at_risk": GLOBAL_META.get("at_risk", ""),
        "detail_rows": GLOBAL_META.get("detail_rows", str(len(DETAIL_ROWS))),
        "updated": GLOBAL_META.get("updated", ""),
        "decision": GLOBAL_META.get("decision", ""),
        "guardrail": GLOBAL_META.get("guardrail", ""),
    }
